### ISSUE TITLE
Status update on Debian

### ISSUE THREAD

**Issue by Maryse47** [xairy/unlockdown#1]
Here's ticket for fedora which you may add in readme: https://bugzilla.redhat.com/show_bug.cgi?id=1800859

Fedora fixed this in all supported branches:

https://src.fedoraproject.org/rpms/kernel/c/7931e3d890b966ab879c1878b4ed31373298978b?branch=master

https://src.fedoraproject.org/rpms/kernel/c/d7d00d12af89d70ff64ba9f4ecf3691c7b8a9453?branch=f31

https://src.fedoraproject.org/rpms/kernel/c/fd6ba4ca25cbb9a39cdac549d18fd8489a9b62ee?branch=f30

**Comment by Maryse47** [comment]
Debian fixed it only in git master branch for now: https://salsa.debian.org/kernel-team/linux/commit/2204f19825db3d7cc3cbce9e37b53720437a3e7e

**Comment by xairy** [comment]
Updated with f54105088ec113a6e619bdc28c74deee2f6cdbe3, thanks!

**Comment by Maryse47** [comment]
@xairy thx, however you put it a bit too optimistic 😄 . For debian I wrote **only the master** git branch has the fix. In other words all of released versions (stable, testing, unstable) are still affected:

https://salsa.debian.org/kernel-team/linux/tree/sid/debian/patches/features/all/lockdown

https://salsa.debian.org/kernel-team/linux/tree/buster/debian/patches/features/all/lockdown

They didn't decided if stable will be fixed yet: https://salsa.debian.org/kernel-team/linux/merge_requests/205

As for ubuntu, they have so many different kernels (standard, hwe, etc.) and distro versions that I don't know if all of them were fixed.

**Comment by xairy** [comment]
> @xairy thx, however you put it a bit too optimistic  . For debian I wrote **only the master** git branch has the fix. In other words all of released versions (stable, testing, unstable) are still affected:
> 
> https://salsa.debian.org/kernel-team/linux/tree/sid/debian/patches/features/all/lockdown
> 
> https://salsa.debian.org/kernel-team/linux/tree/buster/debian/patches/features/all/lockdown
> 
> They didn't decided if stable will be fixed yet: https://salsa.debian.org/kernel-team/linux/merge_requests/205

Ah, OK, thanks for clarification, fixed! Let's keep this issue open and monitor Debian for now.

> 
> As for ubuntu, they have so many different kernels (standard, hwe, etc.) and distro versions that I don't know if all of them were fixed.

Yeah, could be that not all of them are fixed. I don't want to spend time figuring that out though.

**Comment by Maryse47** [comment]
Debian fixed it in [buster](https://salsa.debian.org/kernel-team/linux/-/commit/c0f84a03f23b6d9beb72448e400c10e8071f999e) branch but I think it's not released yet. `sid` remains untouched.

**Comment by xairy** [comment]
Let's consider it fixed on Debian then, I've updated the README. Thanks!
