### ISSUE TITLE
None of these method does not seem to work on Ubuntu 20.04

### ISSUE THREAD

**Issue by gkfirst8** [xairy/unlockdown#2]
I would like to do the 'un-throttling' as seen in https://github.com/erpalma/throttled but my kernel (Linux gkok-ThinkPad-T480 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux) remains in lockdown (it's as if it is afraid of Corona-virus...)

Any help would be greatly appreciated.

**Comment by xairy** [comment]
All of these methods are unintended ways to disable lockdown, and have likely been fixed.

Use the official way of disabling secure boot via `mokutil`.
